services:
    bifrost:
        image: kartoffelchipss/bifrost:latest
        container_name: bifrost
        restart: unless-stopped
        environment:
            DB_DIALECT: sqlite
            FLUXER_BOT_TOKEN_FILE: /root/.creds/bf_flux
            DISCORD_BOT_TOKEN_FILE: /root/.creds/bf_discord
            FLUXER_APPLICATION_ID: 1478333491047665698
            DISCORD_APPLICATION_ID: 1478331623853260892
            COMMAND_PREFIX: "%"
            CONFIG_PATH: /config
            DISCORD_HEALTH_PUSH_URL: http://uptime-kuma:3001/api/push/
            DISCORD_HEALTH_PUSH_TOKEN_FILE: /root/.creds/bf_hc_discord
            FLUXER_HEALTH_PUSH_URL: http://uptime-kuma:3001/api/push/
            FLUXER_HEALTH_PUSH_TOKEN_FILE: /root/.creds/bf_hc_flux
        volumes:
            - bifrost:/config
            - /root/.creds/bf_flux:/root/.creds/bf_flux:ro
            - /root/.creds/bf_discord:/root/.creds/bf_discord:ro
            - /root/.creds/bf_hc_discord:/root/.creds/bf_hc_discord:ro
            - /root/.creds/bf_hc_flux:/root/.creds/bf_hc_flux:ro
        networks:
            - bifrost
            - npm

volumes:
    bifrost:

networks:
    bifrost:
        driver: bridge
    npm:
        external: true
        name: npm_default
