name: Code Quality

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [lint, format:check, build]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run ${{ matrix.task }}